GET http://localhost:8080/autores

###

POST http://localhost:8080/autores

{
    nacionalidade: "fsdfsdf",
}


### 

POST http://localhost:8080/livros

{
    titulo: "dsfhsdf",
    paginas: 0,
    autor: "JRR Tolkien"
}